apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/k3dvol"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
  namespace: keycloak
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: keycloak
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          env:
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KEYCLOAK_HOSTNAME
              value: "iam.fits.cnrs.fr"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: POSTGRES_PASSWORD
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: keycloak-keys
                  key: KC_DB_SCHEMA
            - name: KC_DB_URL_PORT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-keys
                  key: KC_DB_URL_PORT
            - name: KC_HTTPS_CERTIFICATE_FILE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-keys
                  key: SSL_PUBLIC
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-keys
                  key: PRIVATE_KEY
            - name: KC_HTTPS_PROTOCOLS
              valueFrom:
                configMapKeyRef:
                  name: keycloak-keys
                  key: KC_HTTPS_PROTOCOLS
            - name: KC_DB
              valueFrom:
                configMapKeyRef:
                  name: keycloak-keys
                  key: KC_DB
            - name: KC_HTTPS_PORT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-keys
                  key: KC_HTTPS_PORT
            - name: KC_PROXY
              valueFrom:
                configMapKeyRef:
                  name: keycloak-keys
                  key: KC_PROXY
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: keycloak-keys
                  key: KEYCLOAK_ADMIN
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: keycloak-keys
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: keycloak-keys
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: keycloak-keys
                  key: POSTGRES_USER
          volumeMounts:
            - name: task-pv-storage
              mountPath: "/opt/keycloak/demo/certs"
          command:
            - "/opt/keycloak/bin/kc.sh"
          args:
            - "start-dev"
            - "--verbose"
            - "--db=postgres"
            - "--db-url=jdbc:postgresql://$(POSTGRES_HOST):$(KC_DB_URL_PORT)/$(POSTGRES_DB)"
            - "--db-username=$(POSTGRES_USER)"
            - "--db-password=$(POSTGRES_PASSWORD)"
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim