apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: keycloak
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: tls-certs
      mountPath: "/mnt/certs"
      readOnly: true
  volumes:
  - name: tls-certs
    hostPath:
      path: /home/fits/k3s_cluster/test

